version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/learnlink?useSSL=false&createDatabaseIfNotExist=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root_password
      - JWT_SECRET=your_secure_jwt_secret_key_here
      - ALLOWED_ORIGINS=http://localhost:3000
      - FILE_UPLOAD_DIR=/app/uploads
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=learnlink
    volumes:
      - db-data:/var/lib/mysql

volumes:
  uploads:
  db-data:
